### ISSUE TITLE
"android-svc download" doesn't make effect

### ISSUE THREAD

**Issue by wujinjun-MC** [T-vK/android-svc#6]
`android-svc download` downloads all of AIDL files for the current android version,

But after it succeeded I requested 
 commands such as `android-svc list-module` and `android-svc call`, It seemed not to enter offline mode and still took long time to fetch data from Internet.

Is the offline mode broken? Or some configurations required?

**Comment by T-vK** [comment]
Thanks for reporting. It should be fixed in v0.2.2 now.

**Comment by wujinjun-MC** [comment]
Now it works partially after 0.2.2 update, while It looks inconvenient that when I switch to a different directory using `cd`, it doesn't work if no `.android-svc-cache/` exists under the directory

Can it find `.android-svc-cache/` in home directory when the current woking directory doesn't contain it?

**Comment by wujinjun-MC** [comment]
![image](https://github.com/T-vK/android-svc/assets/89054683/9bb99bbb-a70c-41f8-8258-11bb215ecd77)

**Comment by wujinjun-MC** [comment]
![image](https://github.com/T-vK/android-svc/assets/89054683/c80756fd-9395-4fb7-b4a5-b70900ee0d7f)

**Comment by T-vK** [comment]
You're right, this should be fixed in [v0.2.3](https://github.com/T-vK/android-svc/releases/tag/0.2.3).

**Comment by T-vK** [comment]
Feel free to reopen if it's still not working for you.
